[package]
name = "aqpm"
version = "1.1.3-23517"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.4"
os = "0.1.0"
reqwest = {version = "0.11.18", features = ["blocking"]}

